version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '21'
        mavenVersion: 3.6.3
        commands:
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        dependsOn: build_maven
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
  - name: stage-96ad0f94
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: aliyun-server
          hostID:
            - 20af6917-d02c-4e20-a3a2-79324f9d811d
        deployArtifact:
          - source: artifact
            name: output
            target: /home/www/apihub
            artifactRepository: release
            artifactName: output
            artifactVersion: latest
        script:
          - PACKAGE_NAME="api-hub-1.0.0-SNAPSHOT.jar"
          - ''
          - cd /home/www/apihub
          - rm -rf ${PACKAGE_NAME} && tar zxvf output.tar.gz
          - supervisorctl restart apihub
          - echo 'deploy apihub down!'
        notify:
          - certificate: ecdb7a60-fc4b-013b-13a4-4ea0de495936
            events:
              - success
              - fail
              - cancel
              - skip
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: feishu
        strategy:
          retry: '0'
