# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build And Deploy To Aliyun ECS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package -Dmaven.test.skip=true --file pom.xml
    - name: Send to aliyun server        
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_ECS_PRIVATE_KEY }}
        ARGS: "-avzr --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.ALIYUN_ECS_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.ALIYUN_ECS_REMOTE_USER }}
        TARGET: "/home/www/apihub/"
    - name: Deploy on aliyun server
      uses: appleboy/ssh-action@master
      env:
        APP_NAME: "api-hub-1.0.0-SNAPSHOT.jar"
        PACKAGE_NAME: "output.tar.gz"
        TARGET_NAME: "target"
        WORKDIR: "/home/www/apihub"
      with:
        host:  ${{ secrets.ALIYUN_ECS_SERVER_HOST }}
        username: ${{ secret.ALIYUN_ECS_REMOTE_USER }}
        password: ${{ secrets.ALIYUN_ECS_PRIVATE_KEY }}
        script: |          
          cd ${WORKDIR}
          rm -rf APPNAME{APP_NAME} {TARGET_NAME}
          tar xf ${PACKAGE_NAME}
          mv ./TARGETNAME/{TARGET_NAME}/{APP_NAME} ./
          rm -rf PACKAGENAME{PACKAGE_NAME} {TARGET_NAME}
          
          supervisorctl restart apihub
          echo 'deploy apihub done!'
          exit
